name: Wild Teaching
favicon: null
layout_spectrum: 0.25629
typography_spectrum: 0.54299
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101010'
    - '#ffffff'
    - '#667029'
    - '#abafc9'
    - '#c4ef35'
  brandStrength: 0.3125
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
