name: Wild Teaching
favicon: null
layout_spectrum: 0.963541854172945
typography_spectrum: 0.7696740147657692
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.42260608403012156
  lightness: 0.24120895168744028
  saturation: 0.48646983643993735
  rhythmicContrast: 0.25048861373215914
purpose: []
