name: Wild Teaching
favicon: null
layout_spectrum: 0.51147
typography_spectrum: 0.54299
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.1875
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.25048861373215914
purpose: []
